// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function ConnectWiFi(arg1:string,arg2:string):Promise<void>;

export function DisconnectDevice(arg1:string):Promise<void>;

export function GetDeviceInfo(arg1:string):Promise<domain.Device>;

export function GetDeviceOverview(arg1:string):Promise<domain.DeviceInfo>;

export function GetDevices():Promise<Array<domain.Device>>;

export function PairWiFi(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RestartServer():Promise<void>;

export function SetScreenMirrorRect(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<void>;

export function SetScreenMirrorVisible(arg1:string,arg2:boolean):Promise<void>;

export function StartLogcat(arg1:string):Promise<void>;

export function StartScreenMirror(arg1:string,arg2:boolean):Promise<void>;

export function StartShell(arg1:string):Promise<void>;

export function StopLogcat(arg1:string):Promise<void>;

export function StopScreenMirror(arg1:string):Promise<void>;

export function StopShell(arg1:string):Promise<void>;

export function TakeScreenshot(arg1:string):Promise<Array<number>>;

export function WriteShell(arg1:string,arg2:Array<number>):Promise<void>;
