// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildRecordingPath(arg1, arg2) {
  return window['go']['main']['App']['BuildRecordingPath'](arg1, arg2);
}

export function BuildScreenshotPath(arg1, arg2) {
  return window['go']['main']['App']['BuildScreenshotPath'](arg1, arg2);
}

export function ChooseDirectory(arg1) {
  return window['go']['main']['App']['ChooseDirectory'](arg1);
}

export function ChooseRecordingPath(arg1, arg2) {
  return window['go']['main']['App']['ChooseRecordingPath'](arg1, arg2);
}

export function ChooseScreenshotPath(arg1, arg2) {
  return window['go']['main']['App']['ChooseScreenshotPath'](arg1, arg2);
}

export function ConnectWiFi(arg1, arg2) {
  return window['go']['main']['App']['ConnectWiFi'](arg1, arg2);
}

export function DisconnectDevice(arg1) {
  return window['go']['main']['App']['DisconnectDevice'](arg1);
}

export function GetDeviceInfo(arg1) {
  return window['go']['main']['App']['GetDeviceInfo'](arg1);
}

export function GetDeviceOverview(arg1) {
  return window['go']['main']['App']['GetDeviceOverview'](arg1);
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function PairWiFi(arg1, arg2, arg3) {
  return window['go']['main']['App']['PairWiFi'](arg1, arg2, arg3);
}

export function RestartServer() {
  return window['go']['main']['App']['RestartServer']();
}

export function SaveScreenshot(arg1, arg2) {
  return window['go']['main']['App']['SaveScreenshot'](arg1, arg2);
}

export function SetScreenMirrorRect(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetScreenMirrorRect'](arg1, arg2, arg3, arg4, arg5);
}

export function SetScreenMirrorVisible(arg1, arg2) {
  return window['go']['main']['App']['SetScreenMirrorVisible'](arg1, arg2);
}

export function StartLogcat(arg1) {
  return window['go']['main']['App']['StartLogcat'](arg1);
}

export function StartScreenMirror(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartScreenMirror'](arg1, arg2, arg3);
}

export function StartShell(arg1) {
  return window['go']['main']['App']['StartShell'](arg1);
}

export function StopLogcat(arg1) {
  return window['go']['main']['App']['StopLogcat'](arg1);
}

export function StopScreenMirror(arg1) {
  return window['go']['main']['App']['StopScreenMirror'](arg1);
}

export function StopShell(arg1) {
  return window['go']['main']['App']['StopShell'](arg1);
}

export function TakeScreenshot(arg1) {
  return window['go']['main']['App']['TakeScreenshot'](arg1);
}

export function WriteShell(arg1, arg2) {
  return window['go']['main']['App']['WriteShell'](arg1, arg2);
}
